import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Camera, Check, ChevronRight, Copy, Download, Heart, LayoutGrid, Lock, Map, MapPinned, RotateCcw, Share2, Sparkles, Upload } from "lucide-react";

type Mode = "area" | "self";
type Question = { id: string; q: string; options: string[] };
type District = { bn: string; latin: string; division: string };

const divisions: Record<string, string[]> = {
  "ঢাকা বিভাগ": ["কিশোরগঞ্জ","গাজীপুর","গোপালগঞ্জ","টাঙ্গাইল","ঢাকা","নরসিংদী","নারায়ণগঞ্জ","ফরিদপুর","মাদারীপুর","মানিকগঞ্জ","মুন্সীগঞ্জ","রাজবাড়ী","শরীয়তপুর"],
  "চট্টগ্রাম বিভাগ": ["কক্সবাজার","কুমিল্লা","খাগড়াছড়ি","চট্টগ্রাম","চাঁদপুর","নোয়াখালী","ফেনী","বান্দরবান","ব্রাহ্মণবাড়িয়া","রাঙ্গামাটি","লক্ষ্মীপুর"],
  "সিলেট বিভাগ": ["মৌলভীবাজার","সিলেট","সুনামগঞ্জ","হবিগঞ্জ"],
  "বরিশাল বিভাগ": ["ঝালকাঠি","পটুয়াখালী","পিরোজপুর","বরগুনা","বরিশাল","ভোলা"],
  "খুলনা বিভাগ": ["কুষ্টিয়া","খুলনা","চুয়াডাঙ্গা","ঝিনাইদহ","নড়াইল","বাগেরহাট","মাগুরা","মেহেরপুর","যশোর","সাতক্ষীরা"],
  "রাজশাহী বিভাগ": ["চাঁপাইনবাবগঞ্জ","জয়পুরহাট","নওগাঁ","নাটোর","পাবনা","বগুড়া","রাজশাহী","সিরাজগঞ্জ"],
  "রংপুর বিভাগ": ["কুড়িগ্রাম","গাইবান্ধা","ঠাকুরগাঁও","দিনাজপুর","নীলফামারী","পঞ্চগড়","রংপুর","লালমনিরহাট"],
  "ময়মনসিংহ বিভাগ": ["জামালপুর","নেত্রকোণা","ময়মনসিংহ","শেরপুর"]
};
const latinByBn: Record<string, string> = {"বরগুনা":"Barguna","বরিশাল":"Barishal","ভোলা":"Bhola","ঝালকাঠি":"Jhalokati","পটুয়াখালী":"Patuakhali","পিরোজপুর":"Pirojpur","বান্দরবান":"Bandarban","ব্রাহ্মণবাড়িয়া":"Brahmanbaria","চাঁদপুর":"Chandpur","চট্টগ্রাম":"Chattogram","কুমিল্লা":"Cumilla","কক্সবাজার":"Cox's Bazar","ফেনী":"Feni","খাগড়াছড়ি":"Khagrachhari","লক্ষ্মীপুর":"Lakshmipur","নোয়াখালী":"Noakhali","রাঙ্গামাটি":"Rangamati","ঢাকা":"Dhaka","ফরিদপুর":"Faridpur","গাজীপুর":"Gazipur","গোপালগঞ্জ":"Gopalganj","কিশোরগঞ্জ":"Kishorganj","মাদারীপুর":"Madaripur","মানিকগঞ্জ":"Manikganj","মুন্সীগঞ্জ":"Munshiganj","নারায়ণগঞ্জ":"Narayanganj","নরসিংদী":"Narsingdi","রাজবাড়ী":"Rajbari","শরীয়তপুর":"Shariatpur","টাঙ্গাইল":"Tangail","বাগেরহাট":"Bagerhat","চুয়াডাঙ্গা":"Chuadanga","যশোর":"Jashore","ঝিনাইদহ":"Jhenaidah","খুলনা":"Khulna","কুষ্টিয়া":"Kushtia","মাগুরা":"Magura","মেহেরপুর":"Meherpur","নড়াইল":"Narail","সাতক্ষীরা":"Satkhira","জামালপুর":"Jamalpur","ময়মনসিংহ":"Mymensingh","নেত্রকোণা":"Netrokona","শেরপুর":"Sherpur","বগুড়া":"Bogura","জয়পুরহাট":"Joypurhat","নওগাঁ":"Naogaon","নাটোর":"Natore","চাঁপাইনবাবগঞ্জ":"Chapainawabganj","পাবনা":"Pabna","রাজশাহী":"Rajshahi","সিরাজগঞ্জ":"Sirajganj","দিনাজপুর":"Dinajpur","গাইবান্ধা":"Gaibandha","কুড়িগ্রাম":"Kurigram","লালমনিরহাট":"Lalmonirhat","নীলফামারী":"Nilphamari","পঞ্চগড়":"Panchagarh","রংপুর":"Rangpur","ঠাকুরগাঁও":"Thakurgaon","হবিগঞ্জ":"Habiganj","মৌলভীবাজার":"Moulvibazar","সুনামগঞ্জ":"Sunamganj","সিলেট":"Sylhet"};
const districts: District[] = Object.entries(divisions).flatMap(([division, list]) => list.map(bn => ({bn, latin: latinByBn[bn], division})));
const areaQuestions: Question[] = [
  {id:"food", q:"আপনার এলাকার সবচেয়ে honest flex কোনটা?", options:["এক কামড়ে প্রেম","চায়ের আড্ডা","মায়ের রান্না","ঝাল খেয়ে চোখে পানি"]},
  {id:"secret", q:"আপনার এলাকার map-এ secret button কোথায় থাকবে?", options:["পুরোনো মোড়ে","নদীর ধারে","বন্ধুর বাসায়","শুধু local-রা জানে"]},
  {id:"visitor", q:"Visitor-রা আপনার এলাকায় এসে প্রথমে কোন ভুল করে?", options:["রাস্তা ভুলে যায়","ঝালকে ভয় পায় না","ভাষা বুঝে ফেলে ভাবে","বেরোতে চায় না"]},
  {id:"phrase", q:"আপনার এলাকার সবচেয়ে dangerous phrase কোনটি?", options:["একটু বসেন","চা খেয়ে যান","কাল দেখা হবে","রাগ করবেন না"]},
  {id:"memory", q:"আপনার এলাকার কোন scene দেখলে মনে হয়—এটাই home?", options:["বিকেলের আলো","বাজারের শব্দ","বৃষ্টির গন্ধ","রাতের নিরবতা"]},
  {id:"character", q:"আপনার এলাকার unofficial character কে?", options:["চা হাতে philosopher","ঝাল হাতে warrior","নদীর পাশে dreamer","সবাইকে চেনা uncle"]},
  {id:"badge", q:"আপনার এলাকার জন্য কোন badge ঠিক?", options:["Hidden gem","Food capital","Always awake","Memory factory"]},
  {id:"legacy", q:"একটি line-এ আপনার এলাকার গল্প?", options:["এখানে ফিরতেই হয়","এখানে গল্প শেষ হয় না","খাবার আগে, বাকিটা পরে","দূরে গেলেও মনে থাকে"]}
];
const selfQuestions: Question[] = [
  {id:"plan", q:"আপনি group plan-এ কোন character?", options:["Plan করি, যাই না","দেরি করে আগে পৌঁছি","শুধু খাবারে serious","শেষে বলি কাল যাই"]},
  {id:"gallery", q:"আপনার phone gallery খুললে কী বেশি দেখা যাবে?", options:["নিজের ছবি","খাবারের ছবি","Random screenshot","কাউকে না দেখানো ছবি"]},
  {id:"anger", q:"রাগ করলে আপনার most honest reaction কী?", options:["কিছু হয়নি বলি","Seen করে রাখি","Indirect story দিই","পাঁচ মিনিটে নিজেই ফিরি"]},
  {id:"friend", q:"বন্ধুরা আপনাকে কোন কাজে সবচেয়ে বেশি ব্যবহার করে?", options:["Photographer","Food finder","Free therapist","Route planner"]},
  {id:"sit", q:"আপনার কাছে ‘একটু বসি’ মানে কতক্ষণ?", options:["৫ মিনিট","২০ মিনিট","রাত পর্যন্ত","পরের দিনও এখানে"]},
  {id:"warning", q:"আপনার personality-র secret warning কী?", options:["কথা শুরু করলে শেষ নেই","ক্ষুধার্ত হলে dangerous","সব দেখি, reply দিই না","হঠাৎ disappear"]},
  {id:"map", q:"আপনার জীবন যদি একটি map হতো, আপনি কোথায় থাকতেন?", options:["Main road","Hidden shortcut","Food corner","You are here"]},
  {id:"power", q:"আপনার social superpower কোনটি?", options:["অপরিচিতকে বন্ধু করা","সবাইকে খাওয়ানো","যেকোনো কথা joke করা","বিপদে ঠিক route খোঁজা"]}
];
const landmarks: Record<string, string[]> = {"চট্টগ্রাম":["পতেঙ্গা","কর্ণফুলী","পাহাড়তলী"],"সিলেট":["জাফলং","রাতারগুল","লালাখাল"],"কক্সবাজার":["সমুদ্রসৈকত","হিমছড়ি","ইনানী"],"বান্দরবান":["নীলগিরি","বগালেক","স্বর্ণমন্দির"],"ঢাকা":["পুরান ঢাকা","ধানমন্ডি লেক","লালবাগ"],"রাজশাহী":["পদ্মার পাড়","পুঠিয়া","বরেন্দ্র জাদুঘর"]};
const defaultLandmarks = ["পুরোনো মোড়","প্রিয় দোকান","বাড়ির ছাদ"];
const palettes = ["coral","river","mango","night"];

export default function Home() {
  const [mode, setMode] = useState<Mode | null>(null); const [district, setDistrict] = useState("চট্টগ্রাম"); const [search, setSearch] = useState("");
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Record<string,string>>({}); const [name, setName] = useState(""); const [photo, setPhoto] = useState<string | null>(null); const [palette, setPalette] = useState("coral"); const [visible, setVisible] = useState("public");
  const [mapData, setMapData] = useState<any>(null); const [copied, setCopied] = useState(false); const questions = mode === "area" ? areaQuestions : selfQuestions;
  useEffect(() => { fetch("/bd-map.json").then(r => r.json()).then(setMapData).catch(() => undefined); }, []);
  const filteredDistricts = useMemo(() => districts.filter(d => d.bn.includes(search) || d.division.includes(search)), [search]);
  const feature = mapData?.f?.find((f:any) => f.n === latinByBn[district]);
  const activeLandmarks = landmarks[district] || defaultLandmarks;
  const answered = Object.keys(answers).length;
  const resultTitle = mode === "area" ? (answers.badge === "Food capital" ? "The Local Food Capital" : answers.badge === "Hidden gem" ? "The Hidden Gem Keeper" : "The Place You Always Return To") : (answers.map === "Hidden shortcut" ? "The Hidden Shortcut Expert" : answers.map === "Food corner" ? "The Snack-Fuelled Main Character" : answers.warning === "সব দেখি, reply দিই না" ? "The Silent Observer" : "The Unofficial Group Leader");
  const stats = mode === "area" ? [{l:"local pride",v:92},{l:"memory keeper",v:86},{l:"food radar",v:84},{l:"return energy",v:78}] : [{l:"আড্ডাবাজ",v:91},{l:"খাবার-শিকারি",v:88},{l:"spontaneous",v:84},{l:"professional late",v:72}];
  const phrase = mode === "area" ? (answers.phrase || "চা খেয়ে যান") : (answers.warning || "একটু বসি");
  const mapClass = `palette-${palette}`;
  const chooseMode = (next: Mode) => { setMode(next); setStep(0); setAnswers({}); window.setTimeout(() => document.getElementById("maker")?.scrollIntoView({behavior:"smooth"}), 50); };
  const chooseAnswer = (option: string) => { const next = {...answers, [questions[step].id]: option}; setAnswers(next); if (step < questions.length - 1) setStep(step + 1); else setStep(questions.length); };
  const handlePhoto = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => setPhoto(String(reader.result)); reader.readAsDataURL(file); };
  const restart = () => { setStep(0); setAnswers({}); setPhoto(null); setName(""); };
  const share = async () => { const url = `${location.origin}${location.pathname}?mode=${mode}&district=${encodeURIComponent(district)}`; try { if (navigator.share) await navigator.share({title:"আমার এলাকার গল্প", text:`আমি ${district}-এর ${resultTitle}!`, url}); else { await navigator.clipboard.writeText(url); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } } catch { await navigator.clipboard?.writeText(url); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } };
  const download = (kind: "png" | "jpg" | "pdf") => { if (kind === "pdf") { window.print(); return; } const d = feature?.d || "M170,500 L330,350 L460,500 L330,700 Z"; const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#0f624f"/><stop offset="1" stop-color="#e6a07f"/></linearGradient></defs><rect width="1080" height="1350" rx="60" fill="url(#g)"/><text x="80" y="130" fill="white" font-size="28" font-family="Arial">আমার এলাকা · ${mode === "area" ? "এলাকার গল্প" : "আমার সম্পর্কে"}</text><text x="80" y="240" fill="#ffe5a0" font-size="58" font-family="Arial" font-weight="700">${district}</text><text x="80" y="300" fill="white" font-size="32" font-family="Arial">${resultTitle}</text><g transform="translate(210,380) scale(.95)"><path d="${d}" fill="#fff4db44" stroke="#fff4db" stroke-width="5"/></g><text x="80" y="1080" fill="#fff4db" font-size="32" font-family="Arial">${phrase}</text><text x="80" y="1190" fill="white" font-size="22" font-family="Arial">my-area · ${district} · ২০২৬</text></svg>`; const url = URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"})); const img = new Image(); img.onload = () => { const c = document.createElement("canvas"); c.width=1080;c.height=1350; const ctx=c.getContext("2d"); if(!ctx)return;ctx.drawImage(img,0,0);c.toBlob(blob=>{if(!blob)return;const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`amar-area-${district}.${kind}`;a.click();}, kind === "jpg" ? "image/jpeg" : "image/png"); }; img.src=url; };
  return <div className={`app ${mapClass}`}>
    <nav className="nav"><a className="brand" href="#top"><span className="brand-pin">✦</span><span>আমার এলাকা</span></a><div className="nav-links"><a href="#how">কীভাবে কাজ করে</a><a href="#gallery">কার্ড gallery</a><a href="#about">কেন আলাদা?</a></div><a className="nav-cta" href="#maker">শুরু করুন <ArrowRight size={16}/></a></nav>
    <main id="top">
      <section className="hero"><div className="hero-copy"><span className="kicker">YOUR MAP · YOUR STORY</span><h1>আপনার map-এ<br/><em>আপনার গল্প।</em></h1><p>নিজের এলাকা বা নিজের personality বেছে নিন। কয়েকটি মজার প্রশ্নের উত্তর দিন। আপনার জন্য তৈরি করুন একটি shareable animated map card.</p><div className="hero-actions"><a className="primary" href="#maker">আমার card বানান <ArrowRight size={18}/></a><span className="mini-note"><Sparkles size={15}/> ১ মিনিট · ৬৪ জেলা</span></div></div><div className="hero-visual"><div className="hero-map-grid"/><div className="hero-map-outline">{mapData ? <svg viewBox={`0 0 ${mapData.w} ${mapData.h}`}><path d={mapData.f?.[9]?.d} /></svg> : null}<span className="map-label">চট্টগ্রাম</span><i className="landmark-dot dot-a"/><i className="landmark-dot dot-b"/><i className="landmark-dot dot-c"/></div><div className="floating-photo"><div className="fake-photo">🌊</div><span>MY PLACE<br/><b>চট্টগ্রাম</b></span></div><div className="hero-stamp">MAP<br/><b>MY STORY</b></div></div></section>
      <section className="mode-section wrap" id="maker"><div className="section-head"><span className="kicker">01 · CHOOSE YOUR STORY</span><h2>কী ধরনের card বানাবেন?</h2><p>আপনি যে option বেছে নেবেন, প্রশ্ন আর result দুটোই সেই অনুযায়ী বদলে যাবে।</p></div><div className="mode-grid"><button className={`mode-card area-mode ${mode === "area" ? "active" : ""}`} onClick={() => chooseMode("area")}><span className="mode-icon"><MapPinned/></span><span className="mode-number">01</span><h3>আমার এলাকা</h3><p>জেলার map, local food, phrase, landmark আর hometown memory দিয়ে বানান নিজের এলাকার story card.</p><span className="mode-bottom">map-first experience <ChevronRight/></span></button><button className={`mode-card self-mode ${mode === "self" ? "active" : ""}`} onClick={() => chooseMode("self")}><span className="mode-icon"><Sparkles/></span><span className="mode-number">02</span><h3>আমার সম্পর্কে</h3><p>আপনার funny habit, social personality, secret warning আর signature behaviour দিয়ে বানান নিজের card.</p><span className="mode-bottom">personality-first experience <ChevronRight/></span></button></div></section>
      {mode && <section className="maker wrap"><div className="maker-panel"><div className="maker-top"><div><span className="kicker">02 · {mode === "area" ? "AREA STORY" : "SELF STORY"}</span><h2>{mode === "area" ? "আপনার এলাকার গল্প" : "আপনার আসল vibe"}</h2></div><span className="progress">{Math.min(step + 1, questions.length)}/{questions.length}</span></div><div className="stepper"><span className={step > 0 ? "done" : "current"}>01</span><i/><span className={step >= questions.length ? "done" : step > 0 ? "current" : ""}>02</span><i/><span className={step >= questions.length ? "current" : ""}>03</span></div>{step < questions.length ? <div className="question-box"><span className="question-index">QUESTION {String(step + 1).padStart(2,"0")}</span><h3>{questions[step].q}</h3><div className="option-grid">{questions[step].options.map(option => <button key={option} className={answers[questions[step].id] === option ? "option selected" : "option"} onClick={() => chooseAnswer(option)}>{option}<ChevronRight size={16}/></button>)}</div></div> : <div className="setup-box"><span className="question-index">FINAL TOUCH</span><h3>{mode === "area" ? "এখন আপনার area card-টা নিজের করে নিন" : "এখন আপনার personality card-টা নিজের করে নিন"}</h3><div className="setup-row"><input value={name} onChange={e => setName(e.target.value)} placeholder="আপনার নাম বা nickname (optional)"/><label className="photo-upload"><Camera size={17}/> ছবি যোগ করুন<input type="file" accept="image/*" onChange={e => handlePhoto(e.target.files?.[0])}/></label></div><div className="palette-row"><span>কার্ডের mood</span>{palettes.map(p => <button key={p} className={`palette-dot ${p} ${palette === p ? "active" : ""}`} onClick={() => setPalette(p)}/>)}</div><div className="privacy-row"><Lock size={14}/><span>Card visibility</span><button className={visible === "public" ? "vis-active" : ""} onClick={() => setVisible("public")}>Public</button><button className={visible === "link" ? "vis-active" : ""} onClick={() => setVisible("link")}>Link only</button></div><button className="primary wide" onClick={() => document.getElementById("result")?.scrollIntoView({behavior:"smooth"})}>আমার card reveal করুন <Sparkles size={18}/></button></div>}</div><ResultCard mode={mode} district={district} feature={feature} name={name} photo={photo} resultTitle={resultTitle} stats={stats} phrase={phrase} landmarks={activeLandmarks} visible={visible} onShare={share} onDownload={download} copied={copied} onRestart={restart} /></section>}
      <section className="district-section wrap"><div className="section-head"><span className="kicker">03 · PICK A PLACE</span><h2>বাংলাদেশের ৬৪ জেলার map</h2><p>যে জেলা আপনার গল্পের background হবে, সেটি বেছে নিন। প্রতিটি map public geographic vector source থেকে নেওয়া এবং attribution রাখা হয়েছে।</p></div><div className="district-browser"><div className="district-search"><Map size={17}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="জেলা বা বিভাগ খুঁজুন…"/><span>{filteredDistricts.length}/৬৪</span></div><div className="district-grid">{filteredDistricts.map(d => <button key={d.bn} className={district === d.bn ? "district-chip active" : "district-chip"} onClick={() => {setDistrict(d.bn);setSearch("");}}><span className="chip-dot"/>{d.bn}<small>{d.division.replace(" বিভাগ","")}</small></button>)}</div></div></section>
      <section className="how wrap" id="how"><div><span className="kicker">04 · MADE TO BE SHARED</span><h2>একটি card,<br/><em>একটি গল্প।</em></h2></div><div className="how-list"><div><b>01</b><h3>Map বেছে নিন</h3><p>৬৪টি জেলার মধ্যে নিজের area select করুন—সঙ্গে আসবে actual district boundary.</p></div><div><b>02</b><h3>নিজের উত্তর দিন</h3><p>Area mode বা Self mode-এ funny, relatable question-এর উত্তর দিন.</p></div><div><b>03</b><h3>Share করে দেখুন</h3><p>PNG, JPG বা animated reveal share করুন। বন্ধুকে বলুন—“আমার area guess করো।”</p></div></div></section>
      <section className="gallery wrap" id="gallery"><div className="section-head"><span className="kicker">05 · COMMUNITY WALL</span><h2>মানুষ কী বানাচ্ছে?</h2><p>চূড়ান্ত product-এ public card gallery, district battle ও friend comparison থাকবে।</p></div><div className="gallery-grid"><div className="gallery-card big-g"><span>MY AREA STORY</span><b>চট্টগ্রাম</b><small>পাহাড় · সমুদ্র · মেজবান</small></div><div className="gallery-card pink-g"><span>MY SECRET WARNING</span><b>“একটু বসি”</b><small>কিন্তু উঠি কালকে</small></div><div className="gallery-card yellow-g"><span>MAP MEMORY</span><b>সিলেট</b><small>চা হাতে বাড়ি ফেরার জায়গা</small></div></div></section>
    </main>
    <footer id="about"><div className="brand"><span className="brand-pin">✦</span> আমার এলাকা</div><p>তোমার map-এ তোমার গল্প। · Map data attribution: Open geographic vector sources / Natural Earth-style public data.</p><span>Public / Link only / Private</span></footer>
  </div>;
}

function ResultCard({mode,district,feature,name,photo,resultTitle,stats,phrase,landmarks,visible,onShare,onDownload,copied,onRestart}:{mode:Mode;district:string;feature:any;name:string;photo:string|null;resultTitle:string;stats:{l:string;v:number}[];phrase:string;landmarks:string[];visible:string;onShare:()=>void;onDownload:(k:"png"|"jpg"|"pdf")=>void;copied:boolean;onRestart:()=>void}) {
  return <div className="result-wrap" id="result"><div className="result-card"><div className="result-noise"/><div className="result-top"><span className="result-brand"><span className="small-pin">✦</span> আমার এলাকা</span><span className="card-id">{mode === "area" ? "AREA STORY" : "SELF STORY"} · 000127</span></div><div className="result-heading"><span className="kicker">YOUR MAP · YOUR STORY</span><h2>{district}</h2><p>{mode === "area" ? "আমার এলাকার গল্প" : "আমার সম্পর্কে"}</p></div><div className="result-map">{feature && <svg viewBox="0 0 600 828" aria-label={`${district} জেলা map`}><path d={feature.d}/></svg>}<div className="map-lines"/><span className="map-water">{landmarks[0]}</span><span className="map-water second">{landmarks[1]}</span><i className="result-dot d1"/><i className="result-dot d2"/><i className="result-dot d3"/>{photo ? <img className="result-photo" src={photo} alt="আপনার যোগ করা ছবি"/> : <div className="result-photo placeholder"><Camera size={23}/><span>আপনার ছবি</span></div>}<div className="compass">N<br/><b>✦</b></div></div><div className="result-copy"><span className="result-eyebrow">{name || "YOUR PERSONAL RESULT"}</span><h3>{resultTitle}</h3><div className="stat-row">{stats.map(s => <div key={s.l}><b>{s.v}%</b><span>{s.l}</span></div>)}</div><div className="signature"><small>YOUR SIGNATURE LINE</small><strong>“{phrase}”</strong></div></div><div className="result-bottom"><span>{visible === "public" ? "Public card" : "Link only"} · ২০২৬</span><span>guess my {mode === "area" ? "area" : "vibe"} ↗</span></div></div><div className="result-actions"><div className="action-heading"><div><span className="kicker">03 · YOUR CARD</span><h3>রেডি। এবার share করুন।</h3></div><button className="icon-round" onClick={onRestart} aria-label="আবার শুরু"><RotateCcw size={16}/></button></div><div className="action-buttons"><button onClick={onShare}><Share2 size={16}/> {copied ? "Link copied" : "Share card"}</button><button onClick={() => onDownload("png")}><Download size={16}/> PNG</button><button onClick={() => onDownload("jpg")}><Download size={16}/> JPG</button><button onClick={() => onDownload("pdf")}><Download size={16}/> PDF</button></div><p><Heart size={14}/> Card-এ area সরাসরি reveal না করে “guess” hook যোগ করলে share আরও মজার হয়।</p><div className="privacy-note"><Lock size={14}/> {visible === "public" ? "Public card: share link খুললে সবাই দেখতে পারবে।" : "Link-only card: link যাদের দেবেন, তারাই দেখবে।"}</div></div></div>;
}
